

//#import "NCFGradientFilter.h"

#import "UIImage+NC.h"
#import "NCImageFilter.h"
#import "NCVideoCamera.h"
#import "NCRotationFilter.h"
#import "NCNormalFilter.h"
#import "NCFNewFilter.h"
#import "IFNewTwoFIlter.h"
#import "IFAmaroFilter.h"
#import "IFBrannanFilter.h"
#import "IFHefeFilter.h"
#import "IFInkwellFilter.h"
#import "IFLordKelvinFilter.h"
#import "IFXproIIFilter.h"
#import "FC_FogRectangularFilter.h"
#import "GPUImageGaussianBlurFilter.h"
#import "FC_FogFilterGroup.h"
#import "GPUImageFilter.h"
#import "FC_FogCircleFilter.h"
#import "IFNewTfFilter.h"
#import "IFNewTfTwoFilter.h"
#import "IFShadowFilter.h"